[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.21.0",
    "aiohttp>=3.12.15",
    "google-genai>=1.28.0",
    "langdetect>=1.0.9",
    "python-dotenv>=1.1.1",
]
